class UI {
  constructor(){ this.message=''; this.messageTime=0; }
  toast(t){ this.message=t; this.messageTime=1.4; }
  update(dt){ this.messageTime=Math.max(0,this.messageTime-dt); }
  plaque(ctx,x,y,w,h){ ctx.fillStyle='rgba(16,10,6,.88)'; ctx.fillRect(x,y,w,h); ctx.strokeStyle=CONFIG.COLORS.gold; ctx.lineWidth=3; ctx.strokeRect(x+2,y+2,w-4,h-4); }
  drawHud(ctx,game){ const p=game.player; this.plaque(ctx,24,22,390,112); ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='24px Georgia'; ctx.fillText('Masayoshi 正義',44,55); ctx.fillStyle='#220b09'; ctx.fillRect(44,68,250,14); ctx.fillStyle=CONFIG.COLORS.vermillion; ctx.fillRect(44,68,250*(p.hp/p.maxHp),14); ctx.fillStyle='#0d1c22'; ctx.fillRect(44,88,250,10); ctx.fillStyle='#39b7d2'; ctx.fillRect(44,88,250*(p.meter/p.meterMax),10); ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='12px Georgia'; ctx.fillText('HP',305,80); ctx.fillText('Spirit',305,99); const active=game.elements.active(); ctx.fillStyle=active?active.color:CONFIG.COLORS.cream; ctx.fillText(active?active.name+' '+active.display.toUpperCase()+' IMBUED':'Spirit ready',44,119); this.plaque(ctx,930,22,326,64); ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='25px Georgia'; ctx.fillText('SUMI — INK AND STEEL',950,61); const alive=game.enemies.filter(e=>!e.dead).length; this.plaque(ctx,1010,604,236,84); ctx.font='18px Georgia'; ctx.fillText('Encounter '+game.wave+'  Enemies '+alive,1030,634); ctx.fillText(game.chapterTitle || 'Chapter 1',1030,660); if(game.comboCount>1 && game.comboTime>0){ ctx.fillStyle=CONFIG.COLORS.gold; ctx.font='24px Georgia'; ctx.fillText(game.comboCount+' hit carving',1030,684); } if(this.messageTime>0){ ctx.save(); ctx.globalAlpha=Math.min(1,this.messageTime*2); this.plaque(ctx,440,96,400,46); ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='22px Georgia'; ctx.textAlign='center'; ctx.fillText(this.message,640,126); ctx.restore(); } }
  drawMenu(ctx,game){ this.overlay(ctx,'SUMI — INK AND STEEL','Enter: Chapter 1 — The Burning Dojo / 1-3 load saves'); const saves=game.save?.list?.()||[]; ctx.save(); ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='16px Georgia'; ctx.textAlign='center'; saves.forEach((s,i)=>ctx.fillText((i+1)+': '+(s.data?s.data.name+' — '+new Date(s.data.timestamp).toLocaleString():'empty'),640,438+i*24)); ctx.restore(); }
  overlay(ctx,title,sub){ ctx.save(); ctx.fillStyle='rgba(0,0,0,.45)'; ctx.fillRect(0,0,CONFIG.W,CONFIG.H); this.plaque(ctx,350,230,580,220); ctx.textAlign='center'; ctx.fillStyle=CONFIG.COLORS.cream; ctx.font='42px Georgia'; ctx.fillText(title,640,300); ctx.font='22px Georgia'; ctx.fillText(sub,640,350); ctx.font='16px Georgia'; ctx.fillText('Move · J light · K heavy · Shift dodge · Space jump · P pause',640,395); ctx.restore(); }
}
window.UI=UI;
