import * as THREE from 'three';
import { BossBase } from './baseBoss.js';

export class SegmentedDragonBoss extends BossBase {
  constructor(scene, position, name='GODARNI') { super(scene, position, { name, health: 44, radius: 3.8, scoreValue: 3200 }); this._build(); this._addWeakPointRing(new THREE.Vector3(0,0,-2.6),3.3,0xffffaa); }
  _build(){ const body=this._mat(0x8a2e50,{emissive:0x280010,emissiveIntensity:.25,flatShading:true}); const headMat=this._mat(0xff7755,{emissive:0x551100,emissiveIntensity:.45,flatShading:true}); this.segments=[]; for(let i=0;i<9;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(2.7-i*.12,16,10), i===0?headMat:body); m.position.z=i*3.2; m.position.y=Math.sin(i*.8)*.9; this.group.add(m); this.segments.push(m);} for(const side of [-1,1]){const horn=new THREE.Mesh(new THREE.ConeGeometry(.45,2.5,8),this._mat(0xffe0aa)); horn.position.set(side*1.4,1.8,-2.0); horn.rotation.z=-side*.35; this.group.add(horn);} }
  update(dt, player, ctx={}){ super.update(dt,player,ctx); this.position.x=Math.sin(this.t*.85)*9; this.position.y=2+Math.sin(this.t*1.2)*3; this.position.z=-92+Math.sin(this.t*.55)*8; for(let i=0;i<this.segments.length;i++){this.segments[i].position.x=Math.sin(this.t*3+i*.75)*1.8; this.segments[i].position.y=Math.sin(this.t*2+i*.55)*.9;} this._facePlayer(player); this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=Math.max(.55,1.35-this.phase*.18); this._fireAt(player,ctx,'fireball',1.0,new THREE.Vector3(0,0,-3)); if(this.health<this.maxHealth*.45) this._fireAt(player,ctx,'bullet',1.0,new THREE.Vector3(2,0,-1));} }
  canBeHit(hitInfo = null){ return !hitInfo || hitInfo.sphere?.part === 'head'; }
  getHitSpheres(){return [{center:this.position.clone().add(new THREE.Vector3(0,0,-2)), radius:4.2, part:'head', vulnerable:true},{center:this.position.clone().add(new THREE.Vector3(0,0,10)), radius:3.2, part:'body', vulnerable:false}];}
}

export class DomWaveBoss extends BossBase {
  constructor(scene, position, name = 'DOM WAVE') { super(scene, position, { name, health:36, radius:4.2, scoreValue:2600 }); this._build(); this._addWeakPointRing(new THREE.Vector3(0,3.45,-1.3),1.7,0xff99aa); }
  _build(){ const green=this._mat(0x42b35f,{metalness:.25}); const dark=this._mat(0x17251c,{metalness:.35}); const visor=new THREE.MeshBasicMaterial({color:0xff3344}); const torso=new THREE.Mesh(new THREE.BoxGeometry(4,5,2.2),green); this.group.add(torso); const head=new THREE.Mesh(new THREE.BoxGeometry(3,2,2),green); head.position.y=3.4; this.group.add(head); const eye=new THREE.Mesh(new THREE.BoxGeometry(2,.35,.18),visor); eye.position.set(0,3.5,-1.1); this.group.add(eye); for(const x of [-2.8,2.8]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.8,4,.8),dark); arm.position.x=x; this.group.add(arm);} }
  update(dt, player, ctx={}){ super.update(dt,player,ctx); this.position.x=Math.sin(this.t*1.1)*13; this.position.y=Math.sin(this.t*1.7)*4+1; this.position.z=-82+Math.sin(this.t*.8)*10; this.group.rotation.z=Math.sin(this.t*3)*.12; this._facePlayer(player); this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=.8; for(const x of [-2,0,2]) this._fireAt(player,ctx,'missile',.92,new THREE.Vector3(x,.5,-1.5));} }
}

export class ShieldedFaceBoss extends BossBase {
  constructor(scene, position, name='SHURA MIRROR') { super(scene, position, { name, health:42, radius:4.6, scoreValue:3400 }); this.openAmount=0; this._build(); this._addWeakPointRing(new THREE.Vector3(0,0,-1.45),3.8,0xffd98a); }
  _build(){ const stone=this._mat(0x9d8d82,{roughness:.86,flatShading:true}); const eye=new THREE.MeshBasicMaterial({color:0xff3344}); const face=new THREE.Mesh(new THREE.BoxGeometry(6.2,6.8,2.4),stone); this.group.add(face); for(const x of[-1.5,1.5]){const e=new THREE.Mesh(new THREE.BoxGeometry(.8,.46,.24),eye); e.position.set(x,1.1,-1.32); this.group.add(e);} const mouth=new THREE.Mesh(new THREE.BoxGeometry(2.7,.38,.24),eye); mouth.position.set(0,-1.25,-1.32); this.group.add(mouth); this.shields=[]; for(let i=0;i<5;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(1.1,0),stone); this.group.add(rock); this.shields.push(rock);} this._enableShadows?.(); }
  canBeHit(hitInfo = null){ return this.openAmount>.54 && super.canBeHit(hitInfo); }
  update(dt,player,ctx={}){ super.update(dt,player,ctx); this.position.set(Math.sin(this.t*.75)*8,1+Math.sin(this.t*1.2)*2.5,-84+Math.sin(this.t*.6)*6); this.openAmount=(Math.sin(this.t*1.7)+1)/2; const r=5.2-this.openAmount*1.4; for(let i=0;i<this.shields.length;i++){const a=this.t*1.8+i/this.shields.length*Math.PI*2; this.shields[i].position.set(Math.cos(a)*r,Math.sin(a)*r*.72,Math.sin(a)*1.2-1.2); this.shields[i].rotation.x+=dt*2; this.shields[i].rotation.y+=dt*2.4;} this._facePlayer(player); this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=this.openAmount>.54?.72:1.15; const type=this.openAmount>.54?'bullet':'fireball'; for(const off of [new THREE.Vector3(-1.8,.8,-2),new THREE.Vector3(1.8,.8,-2)]) this._fireAt(player,ctx,type,1.0,off);} }
  getHitSpheres(){ return [{center:this.position.clone().add(new THREE.Vector3(0,0,-1.2)), radius:4.8, part:'face', vulnerable:true}]; }
}

export class CarrierBoss extends BossBase {
  constructor(scene, position, name='STANLEY CARRIER') { super(scene, position, { name, health:58, radius:6.2, scoreValue:4200 }); this.portOpen=0; this._build(); this._addWeakPointRing(new THREE.Vector3(0,0,-3.4),1.8,0x9fffff); }
  _build(){ const hull=this._mat(0x6d7484,{metalness:.42,roughness:.36}); const glow=new THREE.MeshBasicMaterial({color:0x66e6ff}); const body=new THREE.Mesh(new THREE.BoxGeometry(11,3.8,5.5),hull); this.group.add(body); const nose=new THREE.Mesh(new THREE.ConeGeometry(2.7,4.2,8),hull); nose.rotation.x=-Math.PI/2; nose.position.z=-4.5; this.group.add(nose); this.reactor=new THREE.Mesh(new THREE.SphereGeometry(1.2,14,10),glow); this.reactor.position.set(0,0,-3.15); this.group.add(this.reactor); for(const x of[-4.2,4.2]){const wing=new THREE.Mesh(new THREE.BoxGeometry(4.8,.35,3.2),hull); wing.position.x=x; wing.position.z=.8; this.group.add(wing);} }
  canBeHit(hitInfo = null){ return this.portOpen>.35 && super.canBeHit(hitInfo); }
  update(dt,player,ctx={}){ super.update(dt,player,ctx); this.position.set(Math.sin(this.t*.55)*7,2+Math.sin(this.t*.85)*2.2,-88+Math.sin(this.t*.45)*5); this.portOpen=(Math.sin(this.t*1.45)+1)/2; this.reactor.scale.setScalar(.75+this.portOpen*.75); this._facePlayer(player); this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=.55+Math.max(0,.45-this.portOpen*.3); for(const off of [new THREE.Vector3(-3,0,-3),new THREE.Vector3(3,0,-3),new THREE.Vector3(0,1.2,-3.4)]) this._fireAt(player,ctx,this.portOpen>.55?'missile':'bullet',1.0,off);} }
  getHitSpheres(){ return [{center:this.position.clone().add(new THREE.Vector3(0,0,-3)), radius:2.4, part:'reactor', vulnerable:true},{center:this.position.clone(), radius:5.8, part:'hull', vulnerable:false}]; }
}

export class FormationBoss extends BossBase {
  constructor(scene, position, name='LOWRYS SWARM') { super(scene, position, { name, health:48, radius:7.5, scoreValue:3600 }); this._build(name); this._addWeakPointRing(new THREE.Vector3(0,0,-2),7.4,0x99ddff); }
  _build(name){ this.units=[]; const mat=this._mat(name.includes('TETRA')?0x66e6ff:0x668cff,{emissive:0x112266,emissiveIntensity:.45,flatShading:true}); for(let i=0;i<8;i++){const geo=name.includes('TETRA')?new THREE.TetrahedronGeometry(2.1):new THREE.CapsuleGeometry(1.0,2.4,6,12); const m=new THREE.Mesh(geo,mat); this.group.add(m); this.units.push(m);} }
  update(dt, player, ctx={}){ super.update(dt,player,ctx); this.position.set(0,2,-88); const r=9+Math.sin(this.t)*2; for(let i=0;i<this.units.length;i++){const a=this.t*1.4+i/this.units.length*Math.PI*2; this.units[i].position.set(Math.cos(a)*r,Math.sin(a*1.3)*5,Math.sin(a)*3); this.units[i].rotation.x+=dt*2; this.units[i].rotation.y+=dt*3;} this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=.65; const a=this.t*2; this._fireAt(player,ctx,'bullet',1.05,new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*4,-2));} }
  getHitSpheres(){return this.units.map(u=>({center:this.position.clone().add(u.position), radius:2.4}));}
}

export class WiWiJumboBoss extends BossBase {
  constructor(scene, position) { super(scene, position, { name:'WI WI JUMBO', health:70, radius:5.5, scoreValue:6000 }); this._build(); this._addWeakPointRing(new THREE.Vector3(0,5.4,-1.9),2.4,0xfff0a0); }
  _build(){ const robe=this._mat(0x5a236b,{emissive:0x220033,emissiveIntensity:.35}); const gold=this._mat(0xffc45b,{metalness:.25,emissive:0x442200,emissiveIntensity:.25}); const body=new THREE.Mesh(new THREE.CylinderGeometry(2.4,3.4,8,12),robe); this.group.add(body); const head=new THREE.Mesh(new THREE.SphereGeometry(2.0,16,12),gold); head.position.y=5.4; this.group.add(head); const halo=new THREE.Mesh(new THREE.TorusGeometry(4.2,.16,8,32),gold); halo.position.y=5.8; halo.rotation.x=Math.PI/2; this.group.add(halo); this.orbs=[]; for(let i=0;i<4;i++){const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(1.0,0),gold); this.group.add(orb); this.orbs.push(orb);} }
  update(dt, player, ctx={}){ super.update(dt,player,ctx); this.position.set(Math.sin(this.t*.7)*10,2+Math.sin(this.t*1.1)*4,-82+Math.sin(this.t*.5)*7); this._facePlayer(player); for(let i=0;i<this.orbs.length;i++){const a=this.t*2+i*Math.PI*.5; this.orbs[i].position.set(Math.cos(a)*5,2+Math.sin(a)*3,Math.sin(a)*2); } this.fireTimer-=dt; if(this.fireTimer<=0){this.fireTimer=this.health<this.maxHealth*.5?.45:.75; for(const off of [new THREE.Vector3(-2,2,-2),new THREE.Vector3(2,2,-2)]) this._fireAt(player,ctx,this.health<this.maxHealth*.5?'missile':'fireball',1.05,off);} }
}
