(() => {
'use strict';
const $=id=>document.getElementById(id), c=$('c'), ctx=c.getContext('2d'), out=$('out');
const REV='roomeditor2';
const clone=o=>JSON.parse(JSON.stringify(o||{}));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clean=s=>(s||'').split('?')[0];
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.floor(Math.random()*9999).toString(36);
// bootstrap.js declares `const PHASE2_DATA = {...}`. A top-level const lives in the
// global lexical scope, NOT on window, so window.PHASE2_DATA is undefined. Read the
// lexical global first, fall back to window for any older bootstrap build.
const BOOT_DATA=(typeof PHASE2_DATA!=='undefined'&&PHASE2_DATA)?PHASE2_DATA:(window.PHASE2_DATA||{});
let project=normalizeProject(clone(BOOT_DATA));
try{ const saved=localStorage.getItem('sumiRoomEditorProject'); if(saved){ const s=JSON.parse(saved); if(s?.levels) project=mergeProject(project,s); } }catch(e){ console.warn(e); }
let currentLevelId=project.level_sequence?.levels?.[0] || project.level_sequence?.start || Object.keys(project.levels)[0];
let currentRoomId=currentLevelId;
let mode='map', tool='select', selected=null, drag=null, linkFrom=null, pointer={x:0,y:0}, spaceDown=false;
let view={x:-120,y:-120,z:.62};
let images={}, lastStatus='Ready';
const helps={
  map_select:'Level Map: click a room box, drag to move it, drag its lower-right corner to resize. Box size is playable room size.',
  map_room:'Click empty space to create a new room box. The new box immediately becomes a playable room in this level.',
  map_link:'Click the source room, then the destination room. The editor creates linked E-door markers in both rooms.',
  map_pan:'Drag to move around the level map.',
  room_select:'Room Edit: click backgrounds, path dots, exits, enemies, objects, or the blue player start. Drag to move.',
  room_background:'Click Fill open room to load the selected background into this room box.',
  room_path:'Click Add default path, then drag white points. Double-click path edges to add points. Alt-click deletes.',
  room_route:'Click where a door/exit prompt should appear. Choose the target room on the right.',
  room_enemy:'Click in the room to place the selected enemy or NPC spawn.',
  room_item:'Click in the room to place the selected object, key, switch, or pickup.',
  room_pan:'Drag to move the view.'
};
function status(msg,obj){ lastStatus=msg; $('status').textContent=msg; out.textContent=obj===undefined?msg:(msg+'\n'+JSON.stringify(obj,null,2)); }
function normalizeProject(p){
  p.config=p.config||{}; p.config.assets=p.config.assets||{}; p.level_sequence=p.level_sequence||{levels:[],rooms:[],start:null}; p.levels=p.levels||{};
  for(const [k,v] of Object.entries(p)){ if(k.startsWith('level_') && v && typeof v==='object' && k!=='level_sequence'){ const id=v.id||k.replace(/^level_/,''); p.levels[id]=v; } }
  for(const [id,l] of Object.entries(p.levels)){ l.id=l.id||id; ensureLevel(l); }
  syncSequence(p);
  return p;
}
function mergeProject(base,s){ base.config=s.config||base.config; base.levels={...base.levels,...(s.levels||{})}; base.level_sequence=s.level_sequence||base.level_sequence; return normalizeProject(base); }
function syncSequence(p=project){
  p.level_sequence=p.level_sequence||{};
  p.level_sequence.levels=Object.keys(p.levels).filter(id=>!p.levels[id].is_room && !p.levels[id].is_level_map_only);
  p.level_sequence.rooms=Object.keys(p.levels).filter(id=>p.levels[id].is_room);
  if(!p.level_sequence.start || !p.levels[p.level_sequence.start]) p.level_sequence.start=p.level_sequence.levels[0]||Object.keys(p.levels)[0];
}
function ensureLevel(l){
  l.world=l.world||{w:1600,h:720,left:70,right:1530,top:0,bottom:690};
  l.world.w=Math.max(420,+l.world.w||1600); l.world.h=Math.max(360,+l.world.h||720);
  l.world.left=+(l.world.left??70); l.world.right=+(l.world.right??(l.world.w-70)); l.world.top=+(l.world.top??0); l.world.bottom=+(l.world.bottom??(l.world.h-30));
  l.player_start=l.player_start||{x:220,y:Math.min(610,l.world.bottom-60),hp:120,meter:35};
  l.backgrounds=l.backgrounds||[]; l.background_segments=l.background_segments||[]; l.walkable_zones=l.walkable_zones||[]; l.route_nodes=l.route_nodes||[]; l.waves=l.waves||[]; l.placed_items=l.placed_items||[]; l.subareas=l.subareas||[];
  l.depth_lanes=l.depth_lanes||{far:Math.round(l.world.h*.38),middle:Math.round(l.world.h*.62),near:Math.round(l.world.h*.82)};
  return l;
}
function ensureRoomLayout(level){
  ensureLevel(level);
  if(!level.room_layout) level.room_layout=[];
  const hasSelf=level.room_layout.some(r=>r.id===level.id);
  if(!hasSelf) level.room_layout.unshift({id:level.id,name:level.name||level.id,x:80,y:100,w:Math.round(level.world.w),h:Math.round(level.world.h),kind:'main',start:true});
  level.room_layout.forEach((r,i)=>{ r.id=r.id||uid('room'); r.name=r.name||r.id.replaceAll('_',' '); r.x=+(r.x??(120+i*340)); r.y=+(r.y??120); r.w=Math.max(420,+(r.w??1280)); r.h=Math.max(360,+(r.h??720)); r.kind=r.kind||'side room'; if(!project.levels[r.id]) project.levels[r.id]=makeRoomFromBox(r, level.id); ensureLevel(project.levels[r.id]); });
  level.room_links=level.room_links||[];
}
function makeRoomFromBox(box,parent){
  return ensureLevel({id:box.id,name:box.name||box.id.replaceAll('_',' '),subtitle:'Room inside '+parent,is_room:box.id!==parent,parent_level:parent,room_kind:box.kind||'side room',world:{w:Math.round(box.w),h:Math.round(box.h),left:70,right:Math.round(box.w)-70,top:0,bottom:Math.round(box.h)-40},player_start:{x:180,y:Math.round(box.h*.68),hp:120,meter:35},backgrounds:[],background_segments:[],walkable_zones:[],route_nodes:[],waves:[],placed_items:[],subareas:[{id:'main',name:box.name||'Room',start:70,end:Math.round(box.w)-70,objective:'Explore this room, defeat threats, solve puzzles, and find exits.'}]});
}
function level(){ return ensureLevel(project.levels[currentLevelId]); }
function room(){ return ensureLevel(project.levels[currentRoomId] || project.levels[currentLevelId]); }
function rooms(){ ensureRoomLayout(level()); return level().room_layout; }
function boxFor(id=currentRoomId){ return rooms().find(r=>r.id===id); }
function resize(){ const r=$('canvasPane').getBoundingClientRect(); c.width=Math.max(320,Math.floor(r.width)); c.height=Math.max(240,Math.floor(r.height)); draw(); } addEventListener('resize',resize);
function worldToScreen(p){ return {x:(p.x-view.x)*view.z, y:(p.y-view.y)*view.z}; }
function screenToWorld(x,y){ return {x:x/view.z+view.x, y:y/view.z+view.y}; }
function mouse(e){ const r=c.getBoundingClientRect(); return screenToWorld(e.clientX-r.left,e.clientY-r.top); }
function currentCenter(){ return screenToWorld(c.width/2,c.height/2); }
function syncZoom(){ $('zoomSlider').value=Math.round(view.z*100); }
function zoomAt(factor,sx=c.width/2,sy=c.height/2){ const before=screenToWorld(sx,sy); view.z=clamp(view.z*factor,.2,2.5); view.x=before.x-sx/view.z; view.y=before.y-sy/view.z; syncZoom(); draw(); }
function fitView(){ if(mode==='map'){ const rs=rooms(); const minX=Math.min(...rs.map(r=>r.x))-100, minY=Math.min(...rs.map(r=>r.y))-100, maxX=Math.max(...rs.map(r=>r.x+r.w))+100, maxY=Math.max(...rs.map(r=>r.y+r.h))+100; view.z=clamp(Math.min(c.width/(maxX-minX),c.height/(maxY-minY)),.2,1.4); view.x=minX; view.y=minY; } else { const r=room(); view.z=clamp(Math.min(c.width/r.world.w,c.height/r.world.h),.2,2.5); view.x=0; view.y=0; } syncZoom(); draw(); }
function setMode(m){ mode=m; selected=null; drag=null; linkFrom=null; $('mapMode').classList.toggle('active',m==='map'); $('roomMode').classList.toggle('active',m==='room'); $('mapTools').style.display=m==='map'?'block':'none'; $('roomTools').style.display=m==='room'?'block':'none'; $('modePill').textContent=m==='map'?'Level Map':'Editing: '+currentRoomId; setTool('select'); refreshAll(); fitView(); }
function setTool(t){ tool=t; document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t && ((mode==='map'&&b.closest('#mapTools'))||(mode==='room'&&b.closest('#roomTools'))))); $('toolHelp').textContent=helps[mode+'_'+t]||''; draw(); }
function getImg(src){ src=clean(src); if(!src) return null; if(!images[src]){ const im=new Image(); im.onload=draw; im.onerror=()=>console.warn('image failed',src); im.src=src+(src.includes('?')?'':'?v='+REV); images[src]=im; } return images[src]; }
function srcForSeg(seg,lvl=room()){ return clean(seg.src || lvl.backgrounds[seg.key_index??seg.keyIndex??0] || ''); }
function saveDraft(){ applyProps(); syncSequence(); localStorage.setItem('sumiRoomEditorProject', JSON.stringify({asset_revision:REV,config:project.config,levels:project.levels,level_sequence:project.level_sequence,enemies:project.enemies,elements:project.elements,modifications:project.modifications,story:project.story})); }
function applyProps(){
  const l=level(); l.name=$('levelName').value||l.name; l.subtitle=$('levelSubtitle').value||l.subtitle;
  const r=room(); r.name=$('roomName').value||r.name; r.room_kind=$('roomType').value||r.room_kind; r.world.w=Math.max(420,+$('roomW').value||r.world.w); r.world.h=Math.max(360,+$('roomH').value||r.world.h); r.world.right=Math.max(r.world.left+100,r.world.w-70); r.world.bottom=Math.max(r.world.top+100,r.world.h-40); r.player_start.x=+$('startX').value||r.player_start.x; r.player_start.y=+$('startY').value||r.player_start.y;
  r.depth_lanes={far:+$('laneFar').value||Math.round(r.world.h*.38), middle:+$('laneMid').value||Math.round(r.world.h*.62), near:+$('laneNear').value||Math.round(r.world.h*.82)};
  const b=boxFor(r.id); if(b){ b.name=r.name; b.kind=r.room_kind; b.w=Math.round(r.world.w); b.h=Math.round(r.world.h); }
}
function addRoomBox(at=null){
  const l=level(); ensureRoomLayout(l); const n=rooms().length+1; const id=uniqueId((currentLevelId+'_room_'+n).toLowerCase()); const p=at||currentCenter();
  const box={id,name:'New Room '+n,x:Math.round(p.x-640),y:Math.round(p.y-360),w:1280,h:720,kind:'side room'}; l.room_layout.push(box); project.levels[id]=makeRoomFromBox(box,currentLevelId); currentRoomId=id; selected={kind:'box',id}; saveDraft(); refreshAll(); status('New room box added. Its box size is now the playable room size.'); }
function uniqueId(base){ let id=base.replace(/[^a-zA-Z0-9_\-]+/g,'_'); let i=2; while(project.levels[id]) id=base+'_'+(i++); return id; }
function openSelectedRoom(){ const id=selected?.kind==='box'?selected.id:currentRoomId; if(!project.levels[id]) return status('Select a room box first.'); currentRoomId=id; setMode('room'); }
function connectRooms(a,b){ if(!a||!b||a===b) return; const l=level(); l.room_links=l.room_links||[]; if(!l.room_links.some(x=>(x.from===a&&x.to===b)||(x.from===b&&x.to===a))) l.room_links.push({from:a,to:b}); addDoorPair(a,b); saveDraft(); refreshAll(); status('Rooms connected with linked E-door markers.',{from:a,to:b}); }
function addDoorPair(a,b){ const A=project.levels[a], B=project.levels[b]; if(!A||!B) return; ensureLevel(A); ensureLevel(B); const ax=Math.max(140,A.world.w-180), ay=Math.round(A.world.h*.68), bx=180, by=Math.round(B.world.h*.68); if(!A.route_nodes.some(n=>n.target_level===b)) A.route_nodes.push({id:uid('route'),type:'side_room',x:ax,y:ay,label:'Door to '+(B.name||b),requires_interact:'E',target_level:b,target_x:bx,target_y:by}); if(!B.route_nodes.some(n=>n.target_level===a)) B.route_nodes.push({id:uid('route'),type:'side_room',x:bx,y:by,label:'Return to '+(A.name||a),requires_interact:'E',target_level:a,target_x:ax-90,target_y:ay}); }
function nearestBox(p){ let best=null; for(const r of rooms().slice().reverse()){ if(p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h){ const corner=Math.hypot(p.x-(r.x+r.w),p.y-(r.y+r.h)); const kind=corner<28/view.z?'boxResize':'box'; best={kind,id:r.id,d:0}; break; } } return best; }
function addBg(src){ const l=room(); src=clean(src||$('bgLibrary').value); if(!src) return status('Pick a background first.'); if(!l.backgrounds.includes(src)) l.backgrounds.push(src); const ki=l.backgrounds.indexOf(src); l.background_segments=[{key_index:ki,src,start:0,end:l.world.w,y:0,h:l.world.h,name:src.split('/').pop().replace(/\..*/, '')}]; selected={kind:'bg',i:0}; saveDraft(); refreshAll(); status('Background filled the open room.'); }
function addPath(){ const l=room(); const y1=Math.round(l.world.h*.58), y2=Math.round(l.world.h*.82), x1=70, x2=l.world.w-70; const z={id:uid('path'),kind:'main_room',points:[[x1,y1],[x2,y1+10],[x2,y2],[x1,y2-8]]}; l.walkable_zones.push(z); selected={kind:'path',zi:l.walkable_zones.length-1}; saveDraft(); refreshAll(); }
function clonePath(){ const l=room(); if(selected?.zi==null) return status('Select a path first.'); const z=clone(l.walkable_zones[selected.zi]); z.id=uid('path'); z.points=z.points.map(p=>[p[0]+40,p[1]+30]); l.walkable_zones.push(z); selected={kind:'path',zi:l.walkable_zones.length-1}; saveDraft(); refreshAll(); }
function addRouteAt(p){ const l=room(); const target=$('routeTarget').value; const rtype=$('routeType').value||'side_room'; const n={id:uid('route'),type:rtype,x:Math.round(p.x),y:Math.round(p.y),label:(rtype==='level_exit'?'LEVEL EXIT':'Door')+(target?' to '+target:''),requires_interact:'E'}; if(target){ n.target_level=target; const t=project.levels[target]; n.target_x=Math.round(t?.player_start?.x||180); n.target_y=Math.round(t?.player_start?.y||Math.round((t?.world?.h||720)*.68)); } l.route_nodes.push(n); selected={kind:'route',i:l.route_nodes.length-1}; if(target) connectRooms(currentRoomId,target); saveDraft(); refreshAll(); }
function addEnemyAt(p){ const l=room(); if(!l.waves.length) l.waves.push({id:uid('wave'),trigger_x:0,gate_x:l.world.w-70,banner:'Room encounter',enemies:[]}); const type=$('enemyType').value||Object.keys(project.enemies||{})[0]||'yakuza_grey_grunt'; l.waves[0].enemies.push({type,x:Math.round(p.x),y:Math.round(p.y)}); selected={kind:'enemy',wi:0,ei:l.waves[0].enemies.length-1}; saveDraft(); refreshAll(); }
function addItemAt(p){ const l=room(); const kind=$('itemKind').value||'health'; const obj={id:uid(kind),kind,x:Math.round(p.x),y:Math.round(p.y)}; if(kind==='switch'||kind==='object'||kind==='npc'){ obj.note=kind==='switch'?'Puzzle switch marker for designer scripting':'Designer marker'; } l.placed_items.push(obj); selected={kind:'item',i:l.placed_items.length-1}; saveDraft(); refreshAll(); }
function nearestPoint(p,limit=16/view.z){ let best=null; (room().walkable_zones||[]).forEach((z,zi)=>(z.points||[]).forEach((q,pi)=>{ const d=Math.hypot(p.x-q[0],p.y-q[1]); if(d<limit&&(!best||d<best.d)) best={kind:'point',zi,pi,d}; })); return best; }
function distSeg(p,a,b){ const abx=b[0]-a[0],aby=b[1]-a[1],len=abx*abx+aby*aby||1; let t=((p.x-a[0])*abx+(p.y-a[1])*aby)/len; t=clamp(t,0,1); const x=a[0]+abx*t,y=a[1]+aby*t; return {x,y,d:Math.hypot(p.x-x,p.y-y)}; }
function nearestEdge(p,limit=24/view.z){ let best=null; (room().walkable_zones||[]).forEach((z,zi)=>{ const pts=z.points||[]; for(let i=0;i<pts.length;i++){ const q=distSeg(p,pts[i],pts[(i+1)%pts.length]); if(q.d<limit&&(!best||q.d<best.d)) best={kind:'edge',zi,pi:i+1,x:q.x,y:q.y,d:q.d}; } }); return best; }
function nearestBg(p){ let best=null; (room().background_segments||[]).forEach((s,i)=>{ const x=s.start??0,y=s.y??0,w=(s.end??(s.start+1280))-x,h=s.h??room().world.h; if(p.x>=x-20&&p.x<=x+w+20&&p.y>=y-20&&p.y<=y+h+20){ const edge=Math.min(Math.abs(p.x-x),Math.abs(p.x-(x+w))); const kind=edge<18/view.z?(Math.abs(p.x-x)<Math.abs(p.x-(x+w))?'bgLeft':'bgRight'):'bg'; best={kind,i,d:edge}; } }); return best; }
function nearestObject(p){ let best=nearestPoint(p)||nearestBg(p); const check=(obj,d)=>{ if(d<35/view.z&&(!best||d<best.d)) best={...obj,d}; }; const l=room(); (l.route_nodes||[]).forEach((n,i)=>check({kind:'route',i},Math.hypot(p.x-n.x,p.y-n.y))); (l.placed_items||[]).forEach((it,i)=>check({kind:'item',i},Math.hypot(p.x-it.x,p.y-it.y))); (l.waves||[]).forEach((w,wi)=>(w.enemies||[]).forEach((e,ei)=>check({kind:'enemy',wi,ei},Math.hypot(p.x-e.x,p.y-e.y)))); if(Math.hypot(p.x-l.player_start.x,p.y-l.player_start.y)<32/view.z) check({kind:'player'},0); return best; }
function deleteSelected(){ if(!selected) return; const l=mode==='map'?level():room(); if(mode==='map'&&selected.kind==='box'){ if(selected.id===currentLevelId) return status('The main room box cannot be deleted.'); l.room_layout=l.room_layout.filter(r=>r.id!==selected.id); l.room_links=(l.room_links||[]).filter(x=>x.from!==selected.id&&x.to!==selected.id); delete project.levels[selected.id]; selected=null; }
  else if(selected.kind==='point'){ const z=l.walkable_zones[selected.zi]; z.points.splice(selected.pi,1); if(z.points.length<3) l.walkable_zones.splice(selected.zi,1); selected=null; }
  else if(selected.kind==='path') { l.walkable_zones.splice(selected.zi,1); selected=null; }
  else if(selected.kind==='bg'||selected.kind==='bgLeft'||selected.kind==='bgRight') { l.background_segments.splice(selected.i,1); selected=null; }
  else if(selected.kind==='route') { l.route_nodes.splice(selected.i,1); selected=null; }
  else if(selected.kind==='enemy') { l.waves[selected.wi].enemies.splice(selected.ei,1); selected=null; }
  else if(selected.kind==='item') { l.placed_items.splice(selected.i,1); selected=null; }
  saveDraft(); refreshAll(); }
async function saveFile(){ saveDraft(); const payload={project:{asset_revision:REV,config:project.config,levels:project.levels,level_sequence:project.level_sequence,enemies:project.enemies,elements:project.elements,modifications:project.modifications,story:project.story}}; try{ const r=await fetch('/api/save-project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok||!j.ok) throw new Error(j.error||r.status); status('Saved to game files. Bootstrap refreshed.',j); }catch(e){ status('Direct save failed. Draft is saved in this browser; run dev_server.py for file saving.',{error:String(e)}); } }
async function uploadBg(){ const f=$('bgFile').files[0]; if(!f) return status('Choose an image first.'); const data=await new Promise(res=>{ const r=new FileReader(); r.onload=()=>res(r.result); r.readAsDataURL(f); }); try{ const r=await fetch('/api/upload-background',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name,data})}); const j=await r.json(); if(!r.ok||!j.ok) throw new Error(j.error||r.status); project.config.assets.background_library=project.config.assets.background_library||[]; project.config.assets.background_library.push({id:j.id,src:j.src,label:j.id}); refreshAll(); $('bgLibrary').value=j.src; status('Uploaded background. Now click Fill open room.',j); }catch(e){ status('Upload failed because direct-save server is not running.',{error:String(e)}); } }
function playLevel(){ saveDraft(); localStorage.setItem('sumiEditorProject', JSON.stringify({asset_revision:REV,config:project.config,levels:project.levels,level_sequence:project.level_sequence,enemies:project.enemies,elements:project.elements,modifications:project.modifications,story:project.story})); localStorage.setItem('sumiEditorPlay', JSON.stringify({levelId:currentRoomId,camX:0,camY:0,waveIndex:0,at:Date.now()})); window.open('index.html?editorPreview=1&testEditor=1&skipIntro=1&level='+encodeURIComponent(currentRoomId)+'&v='+REV,'_blank'); }
function projectSnapshot(){ applyProps(); syncSequence(); return {asset_revision:REV,config:project.config,levels:project.levels,level_sequence:project.level_sequence,enemies:project.enemies,elements:project.elements,modifications:project.modifications,story:project.story}; }
function exportJSON(){ const snap=projectSnapshot(); const blob=new Blob([JSON.stringify(snap,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); const safe=(currentLevelId||'sumi_level').replace(/[^a-z0-9_\-]+/gi,'_'); a.href=url; a.download=safe+'.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),2000); status('Downloaded '+safe+'.json. Keep it or share it; re-import any time.'); }
function importJSON(file){ if(!file) return; const r=new FileReader(); r.onload=()=>{ try{ const s=JSON.parse(r.result); if(!s||!s.levels) throw new Error('No levels in file'); project=mergeProject(project,s); currentLevelId=project.level_sequence?.levels?.[0]||Object.keys(project.levels)[0]; currentRoomId=currentLevelId; saveDraft(); setMode('map'); status('Imported level pack from file. Saved to this browser.'); }catch(e){ status('Could not import that file.',{error:String(e)}); } }; r.readAsText(file); }
function refreshAll(){ ensureRoomLayout(level()); if(!project.levels[currentRoomId]) currentRoomId=currentLevelId; const l=level(), r=room(); $('levelSelect').innerHTML=project.level_sequence.levels.map(id=>`<option value="${id}" ${id===currentLevelId?'selected':''}>${project.levels[id].name||id}</option>`).join(''); $('levelName').value=l.name||''; $('levelSubtitle').value=l.subtitle||''; $('roomSelect').innerHTML=rooms().map(b=>`<option value="${b.id}" ${b.id===currentRoomId?'selected':''}>${b.name||b.id}</option>`).join(''); $('startRoom').innerHTML=rooms().map(b=>`<option value="${b.id}" ${b.start?'selected':''}>${b.name||b.id}</option>`).join(''); $('roomName').value=r.name||''; $('roomType').value=r.room_kind||boxFor(r.id)?.kind||'side room'; $('roomW').value=Math.round(r.world.w); $('roomH').value=Math.round(r.world.h); $('startX').value=Math.round(r.player_start.x); $('startY').value=Math.round(r.player_start.y); $('laneFar').value=Math.round(r.depth_lanes?.far||r.world.h*.38); $('laneMid').value=Math.round(r.depth_lanes?.middle||r.world.h*.62); $('laneNear').value=Math.round(r.depth_lanes?.near||r.world.h*.82);
  const b=selected?.kind==='box'?boxFor(selected.id):boxFor(currentRoomId); if(b){ $('boxX').value=Math.round(b.x); $('boxY').value=Math.round(b.y); $('boxW').value=Math.round(b.w); $('boxH').value=Math.round(b.h); }
  const lib=project.config.assets.background_library||[]; const bgOptions=[...new Map([...(r.backgrounds||[]).map(s=>[clean(s),s]), ...lib.map(b=>[clean(b.src),b.label||b.src])]).entries()]; $('bgLibrary').innerHTML=bgOptions.map(([src,label])=>`<option value="${src}">${label}</option>`).join(''); $('enemyType').innerHTML=Object.keys(project.enemies||{}).concat(['npc_villager']).filter((v,i,a)=>v&&a.indexOf(v)===i).map(e=>`<option>${e}</option>`).join(''); $('routeTarget').innerHTML=[...rooms().filter(b=>b.id!==currentRoomId).map(b=>({id:b.id,name:b.name||b.id,kind:'room'})), ...project.level_sequence.levels.filter(id=>id!==currentLevelId).map(id=>({id,name:(project.levels[id]?.name||id),kind:'level'}))].map(t=>`<option value="${t.id}">${t.kind==='level'?'NEXT LEVEL: ':''}${t.name}</option>`).join(''); refreshLists(); draw(); }
function refreshLists(){ const l=level(), r=room(); $('roomList').innerHTML=rooms().map(b=>`<button data-sel="box:${b.id}" class="${selected?.kind==='box'&&selected.id===b.id?'active':''}"><b>${b.name||b.id}</b><br>${b.id} · ${Math.round(b.w)}×${Math.round(b.h)} · ${b.kind||'room'}${b.start?' · START':''}</button>`).join(''); $('bgList').innerHTML=(r.background_segments||[]).map((s,i)=>`<button data-sel="bg:${i}" class="${selected?.kind==='bg'&&selected.i===i?'active':''}">${i+1}. ${s.name||srcForSeg(s,r)}<br>${Math.round(s.start||0)}→${Math.round(s.end||r.world.w)}</button>`).join('')||'<span class="small">No background in open room yet.</span>'; $('pathList').innerHTML=(r.walkable_zones||[]).map((z,i)=>`<button data-sel="path:${i}" class="${(selected?.kind==='path'||selected?.kind==='point')&&selected.zi===i?'active':''}">${i+1}. ${z.id||'path'} · ${(z.points||[]).length} points</button>`).join('')||'<span class="small">No path yet. Click Add default path.</span>'; $('routeList').innerHTML=(r.route_nodes||[]).map((n,i)=>`<button data-sel="route:${i}" class="${selected?.kind==='route'&&selected.i===i?'active':''}">${i+1}. ${n.label||n.type}<br>${n.target_level?'→ '+n.target_level:'no target'}</button>`).join('')||'<span class="small">No exits yet.</span>'; let sp=[]; (r.waves||[]).forEach((w,wi)=>(w.enemies||[]).forEach((e,ei)=>sp.push(`<button data-sel="enemy:${wi}:${ei}" class="${selected?.kind==='enemy'&&selected.wi===wi&&selected.ei===ei?'active':''}">Enemy ${e.type} @ ${Math.round(e.x)},${Math.round(e.y)}</button>`))); (r.placed_items||[]).forEach((it,i)=>sp.push(`<button data-sel="item:${i}" class="${selected?.kind==='item'&&selected.i===i?'active':''}">${it.kind} @ ${Math.round(it.x)},${Math.round(it.y)}</button>`)); $('spawnList').innerHTML=sp.join('')||'<span class="small">No enemies/objects yet.</span>';
  document.querySelectorAll('[data-sel]').forEach(btn=>btn.onclick=()=>{ const p=btn.dataset.sel.split(':'); if(p[0]==='box'){ selected={kind:'box',id:p[1]}; currentRoomId=p[1]; } if(p[0]==='bg') selected={kind:'bg',i:+p[1]}; if(p[0]==='path') selected={kind:'path',zi:+p[1]}; if(p[0]==='route') selected={kind:'route',i:+p[1]}; if(p[0]==='enemy') selected={kind:'enemy',wi:+p[1],ei:+p[2]}; if(p[0]==='item') selected={kind:'item',i:+p[1]}; refreshAll(); }); refreshSelectedPanel(); }
function refreshSelectedPanel(){ const p=$('selectedPanel'); if(!selected){ p.textContent=mode==='map'?'Select a room box.':'Select a room object, path point, exit, enemy, or item.'; return; } if(selected.kind==='box'){ const b=boxFor(selected.id), r=project.levels[selected.id]; p.innerHTML=`<b>Room box</b><br>${b.name}<br>ID: ${b.id}<br>Box/playable size: ${Math.round(b.w)}×${Math.round(b.h)}<br>Open this room to add background, depth lanes, path, exits, enemies, NPCs, objects, puzzles.`; }
  else if(selected.kind==='point') p.innerHTML=`<b>Path point</b><br>Drag to shape the walkable floor. Alt-click/Delete removes.`;
  else if(selected.kind==='path') p.innerHTML=`<b>Walkable path</b><br>Actors clamp to this polygon.`;
  else if(selected.kind==='route'){ const n=room().route_nodes[selected.i]; p.innerHTML=`<b>Exit / Door</b><br>${n.label||n.type}<br>${n.target_level?'Target: '+n.target_level:'No target'}`; }
  else p.innerHTML='<b>'+selected.kind+'</b>'; }
function drawGrid(step=160){ const minx=Math.floor(view.x/step)*step, maxx=view.x+c.width/view.z, miny=Math.floor(view.y/step)*step, maxy=view.y+c.height/view.z; ctx.strokeStyle='rgba(247,237,207,.07)'; ctx.lineWidth=1/view.z; for(let x=minx;x<maxx;x+=step){ ctx.beginPath(); ctx.moveTo(x,miny); ctx.lineTo(x,maxy); ctx.stroke(); } for(let y=miny;y<maxy;y+=step){ ctx.beginPath(); ctx.moveTo(minx,y); ctx.lineTo(maxx,y); ctx.stroke(); } }
function draw(){ if(!ctx) return; ctx.setTransform(1,0,0,1,0,0); ctx.clearRect(0,0,c.width,c.height); ctx.fillStyle='#050403'; ctx.fillRect(0,0,c.width,c.height); ctx.save(); ctx.scale(view.z,view.z); ctx.translate(-view.x,-view.y); if(mode==='map') drawMap(); else drawRoom(); ctx.restore(); $('hud').innerHTML=`${mode==='map'?'Level map: '+currentLevelId:'Room: '+currentRoomId}<br>tool ${tool} · zoom ${Math.round(view.z*100)}% · pointer ${Math.round(pointer.x)},${Math.round(pointer.y)}<br>${lastStatus}`; $('modeBanner').textContent=helps[mode+'_'+tool]||''; }
function drawMap(){ drawGrid(200); const rs=rooms(); const l=level(); ctx.lineWidth=3/view.z; (l.room_links||[]).forEach(link=>{ const a=boxFor(link.from), b=boxFor(link.to); if(!a||!b) return; ctx.strokeStyle='rgba(110,231,255,.65)'; ctx.setLineDash([18/view.z,10/view.z]); ctx.beginPath(); ctx.moveTo(a.x+a.w/2,a.y+a.h/2); ctx.lineTo(b.x+b.w/2,b.y+b.h/2); ctx.stroke(); ctx.setLineDash([]); }); rs.forEach((r,i)=>{ const sel=selected?.kind==='box'&&selected.id===r.id; ctx.fillStyle=r.id===currentLevelId?'rgba(128,200,120,.22)':'rgba(216,167,66,.15)'; ctx.fillRect(r.x,r.y,r.w,r.h); ctx.strokeStyle=sel?'#fff':'#d8a742'; ctx.lineWidth=(sel?5:3)/view.z; ctx.strokeRect(r.x,r.y,r.w,r.h); ctx.fillStyle=sel?'#fff':'#f7edcf'; ctx.font=`bold ${28/view.z}px Georgia`; ctx.fillText((r.start?'★ ':'')+(r.name||r.id),r.x+18/view.z,r.y+42/view.z); ctx.font=`${18/view.z}px Georgia`; ctx.fillText(`${r.id} · ${Math.round(r.w)}×${Math.round(r.h)} · ${r.kind||'room'}`,r.x+18/view.z,r.y+72/view.z); ctx.fillStyle='#050403'; ctx.fillRect(r.x+r.w-28/view.z,r.y+r.h-28/view.z,24/view.z,24/view.z); ctx.fillStyle='#ffcc38'; ctx.fillRect(r.x+r.w-24/view.z,r.y+r.h-24/view.z,20/view.z,20/view.z); }); if(linkFrom){ const a=boxFor(linkFrom); if(a){ ctx.strokeStyle='#ff2a1a'; ctx.lineWidth=4/view.z; ctx.strokeRect(a.x-8/view.z,a.y-8/view.z,a.w+16/view.z,a.h+16/view.z); } } }
function drawRoom(){ const l=room(); ctx.fillStyle='#100b08'; ctx.fillRect(0,0,l.world.w,l.world.h); ctx.strokeStyle='rgba(247,237,207,.38)'; ctx.lineWidth=3/view.z; ctx.strokeRect(0,0,l.world.w,l.world.h); (l.background_segments||[]).forEach((s,i)=>{ const im=getImg(srcForSeg(s,l)); const x=s.start??0,y=s.y??0,w=(s.end??l.world.w)-x,h=s.h??l.world.h; if(im&&im.complete&&im.naturalWidth) ctx.drawImage(im,x,y,w,h); else {ctx.fillStyle='#1b2a4e';ctx.fillRect(x,y,w,h);ctx.fillStyle='#f7edcf';ctx.fillText('loading '+(s.name||i),x+20,y+30);} ctx.strokeStyle=selected?.kind==='bg'&&selected.i===i?'#fff':'rgba(216,167,66,.75)'; ctx.lineWidth=3/view.z; ctx.strokeRect(x,y,w,h); });
  const lanes=l.depth_lanes||{}; [['FAR / BACK',lanes.far||l.world.h*.38,'rgba(110,231,255,.18)'],['MIDDLE / FIGHT',lanes.middle||l.world.h*.62,'rgba(255,196,48,.15)'],['NEAR / FRONT',lanes.near||l.world.h*.82,'rgba(196,30,58,.14)']].forEach(([name,y,col])=>{ ctx.fillStyle=col; ctx.fillRect(0,y-18,l.world.w,36); ctx.strokeStyle='rgba(255,255,255,.28)'; ctx.lineWidth=1/view.z; ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(l.world.w,y); ctx.stroke(); ctx.fillStyle='#fff'; ctx.font=`${16/view.z}px Georgia`; ctx.fillText(name,18/view.z,y-24/view.z); });
  (l.walkable_zones||[]).forEach((z,zi)=>{ const pts=z.points||[]; if(!pts.length) return; ctx.beginPath(); pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])); ctx.closePath(); ctx.fillStyle='rgba(94,231,255,.2)'; ctx.strokeStyle=(selected?.zi===zi)?'#ffffff':'rgba(247,237,207,.9)'; ctx.lineWidth=3/view.z; ctx.fill(); ctx.stroke(); pts.forEach((p,pi)=>{ ctx.beginPath(); ctx.fillStyle=selected?.kind==='point'&&selected.zi===zi&&selected.pi===pi?'#ff2a1a':'#fff7d4'; ctx.arc(p[0],p[1],8/view.z,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='#050403'; ctx.stroke(); }); });
  (l.route_nodes||[]).forEach((n,i)=>{ ctx.save(); ctx.translate(n.x,n.y); ctx.fillStyle=selected?.kind==='route'&&selected.i===i?'#ff2a1a':'#6ee7ff'; ctx.beginPath(); ctx.arc(0,0,15/view.z,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='#050403'; ctx.lineWidth=3/view.z; ctx.stroke(); ctx.fillStyle='#050403'; ctx.font=`bold ${14/view.z}px Georgia`; ctx.textAlign='center'; ctx.fillText('E',0,5/view.z); ctx.textAlign='left'; ctx.fillStyle='#fff'; ctx.font=`${15/view.z}px Georgia`; ctx.fillText(n.label||n.target_level||'exit',20/view.z,-18/view.z); ctx.restore(); });
  (l.waves||[]).forEach((w,wi)=>(w.enemies||[]).forEach((e,ei)=>{ ctx.fillStyle=selected?.kind==='enemy'&&selected.wi===wi&&selected.ei===ei?'#ffcc38':'#c41e3a'; ctx.fillRect(e.x-13,e.y-44,26,52); ctx.fillStyle='#fff'; ctx.font=`${12/view.z}px Georgia`; ctx.fillText(e.type,e.x+18/view.z,e.y); })); (l.placed_items||[]).forEach((it,i)=>{ ctx.fillStyle=selected?.kind==='item'&&selected.i===i?'#ffcc38':(it.kind==='switch'?'#9a66ff':'#80c878'); ctx.beginPath(); ctx.ellipse(it.x,it.y,13/view.z,18/view.z,0,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#fff'; ctx.font=`${12/view.z}px Georgia`; ctx.fillText(it.kind,it.x+16/view.z,it.y); }); ctx.fillStyle='#6ee7ff'; ctx.beginPath(); ctx.arc(l.player_start.x,l.player_start.y,12/view.z,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#fff'; ctx.font=`${14/view.z}px Georgia`; ctx.fillText('PLAYER START',l.player_start.x+18/view.z,l.player_start.y); }
// input
c.addEventListener('contextmenu',e=>e.preventDefault());
c.addEventListener('mousedown',e=>{ const p=mouse(e); pointer=p; if(e.button===2||tool==='pan'||spaceDown){ drag={kind:'pan',sx:e.clientX,sy:e.clientY,vx:view.x,vy:view.y}; return; } if(e.altKey){ selected=mode==='map'?nearestBox(p):nearestObject(p); deleteSelected(); return; } if(mode==='map'){ const hit=nearestBox(p); if(tool==='room'){ addRoomBox(p); return; } if(tool==='link'){ if(hit?.id){ if(!linkFrom){ linkFrom=hit.id; selected={kind:'box',id:hit.id}; status('Now click the destination room.'); } else { connectRooms(linkFrom,hit.id); linkFrom=null; } refreshAll(); } return; } selected=hit; if(hit){ currentRoomId=hit.id; drag=hit; } refreshAll(); return; }
  if(tool==='background'){ const o=nearestBg(p); if(o){ selected=o; drag=o; } else addBg($('bgLibrary').value); refreshAll(); return; } if(tool==='path'){ const pt=nearestPoint(p); if(pt){ selected=pt; drag=pt; } else { const edge=nearestEdge(p); if(edge){ const z=room().walkable_zones[edge.zi]; z.points.splice(edge.pi,0,[Math.round(edge.x),Math.round(edge.y)]); selected={kind:'point',zi:edge.zi,pi:edge.pi}; drag=selected; } else addPath(); } refreshAll(); return; } if(tool==='route'){ addRouteAt(p); return; } if(tool==='enemy'){ addEnemyAt(p); return; } if(tool==='item'){ addItemAt(p); return; } selected=nearestObject(p); drag=selected; refreshAll(); });
c.addEventListener('dblclick',e=>{ const p=mouse(e); if(mode==='map'){ const hit=nearestBox(p); if(hit?.id){ currentRoomId=hit.id; setMode('room'); } return; } const edge=nearestEdge(p,40/view.z); if(edge){ const z=room().walkable_zones[edge.zi]; z.points.splice(edge.pi,0,[Math.round(edge.x),Math.round(edge.y)]); selected={kind:'point',zi:edge.zi,pi:edge.pi}; saveDraft(); refreshAll(); } });
addEventListener('mouseup',()=>{ if(drag){ drag=null; saveDraft(); refreshAll(); } });
c.addEventListener('mousemove',e=>{ const p=mouse(e); pointer=p; if(!drag){ draw(); return; } if(drag.kind==='pan'){ view.x=drag.vx-(e.clientX-drag.sx)/view.z; view.y=drag.vy-(e.clientY-drag.sy)/view.z; draw(); return; } if(mode==='map'){ const b=boxFor(drag.id); if(!b) return; if(drag.kind==='boxResize'){ b.w=Math.max(420,Math.round(p.x-b.x)); b.h=Math.max(360,Math.round(p.y-b.y)); const r=project.levels[b.id]; if(r){ r.world.w=b.w; r.world.h=b.h; r.world.right=b.w-70; r.world.bottom=b.h-40; } } else if(drag.kind==='box'){ b.x=Math.round(p.x-b.w/2); b.y=Math.round(p.y-b.h/2); } draw(); return; }
  const l=room(); if(drag.kind==='point'){ l.walkable_zones[drag.zi].points[drag.pi]=[Math.round(p.x),Math.round(p.y)]; } else if(drag.kind==='bgLeft'){ const s=l.background_segments[drag.i]; s.start=Math.round(Math.min(p.x,(s.end||s.start+100)-60)); } else if(drag.kind==='bgRight'){ const s=l.background_segments[drag.i]; s.end=Math.round(Math.max(p.x,(s.start||0)+60)); } else if(drag.kind==='bg'){ const s=l.background_segments[drag.i]; const w=(s.end??0)-(s.start??0), h=s.h??l.world.h; s.start=Math.round(p.x-w/2); s.end=Math.round(s.start+w); s.y=Math.round(p.y-h/2); } else if(drag.kind==='route'){ const n=l.route_nodes[drag.i]; n.x=Math.round(p.x); n.y=Math.round(p.y); } else if(drag.kind==='enemy'){ const e2=l.waves[drag.wi].enemies[drag.ei]; e2.x=Math.round(p.x); e2.y=Math.round(p.y); } else if(drag.kind==='item'){ const it=l.placed_items[drag.i]; it.x=Math.round(p.x); it.y=Math.round(p.y); } else if(drag.kind==='player'){ l.player_start.x=Math.round(p.x); l.player_start.y=Math.round(p.y); } draw(); });
c.addEventListener('wheel',e=>{ e.preventDefault(); const r=c.getBoundingClientRect(); zoomAt(Math.exp(-e.deltaY*.0012),e.clientX-r.left,e.clientY-r.top); },{passive:false});
addEventListener('keydown',e=>{ if(e.code==='Space') spaceDown=true; if(e.key==='Delete'||e.key==='Backspace') deleteSelected(); }); addEventListener('keyup',e=>{ if(e.code==='Space') spaceDown=false; });
// buttons
$('helpBtn').onclick=()=>$('helpModal').classList.add('show'); $('closeHelp').onclick=()=>$('helpModal').classList.remove('show'); $('mapMode').onclick=()=>setMode('map'); $('roomMode').onclick=openSelectedRoom; document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool)); $('levelSelect').onchange=e=>{ applyProps(); currentLevelId=e.target.value; ensureRoomLayout(level()); currentRoomId=currentLevelId; setMode('map'); }; $('roomSelect').onchange=e=>{ currentRoomId=e.target.value; selected={kind:'box',id:currentRoomId}; refreshAll(); }; $('startRoom').onchange=e=>{ rooms().forEach(b=>b.start=b.id===e.target.value); saveDraft(); refreshAll(); };
['levelName','levelSubtitle'].forEach(id=>$(id).onchange=()=>{applyProps(); saveDraft(); refreshAll();}); $('applyRoom').onclick=()=>{applyProps(); saveDraft(); refreshAll();}; $('applyLanes').onclick=()=>{applyProps(); saveDraft(); refreshAll();}; $('applyBox').onclick=()=>{ const b=selected?.kind==='box'?boxFor(selected.id):boxFor(currentRoomId); if(!b) return; b.x=+$('boxX').value||b.x; b.y=+$('boxY').value||b.y; b.w=Math.max(420,+$('boxW').value||b.w); b.h=Math.max(360,+$('boxH').value||b.h); const r=project.levels[b.id]; if(r){ r.world.w=b.w; r.world.h=b.h; r.world.right=b.w-70; r.world.bottom=b.h-40; } saveDraft(); refreshAll(); };
$('addRoom').onclick=()=>addRoomBox(); $('openRoom').onclick=openSelectedRoom; $('backToMap').onclick=()=>setMode('map'); $('fitRoom').onclick=fitView; $('newLevel').onclick=()=>{ const id=uniqueId(prompt('New level id:','new_interconnected_level')||'new_interconnected_level'); project.levels[id]=ensureLevel({id,name:'New Interconnected Level',subtitle:'Room-box level',world:{w:1280,h:720,left:70,right:1210,top:0,bottom:680},player_start:{x:180,y:500},room_layout:[],room_links:[]}); currentLevelId=id; currentRoomId=id; syncSequence(); setMode('map'); }; $('duplicateLevel').onclick=()=>{ const id=uniqueId(prompt('Duplicate level as:',currentLevelId+'_copy')||currentLevelId+'_copy'); project.levels[id]=clone(level()); project.levels[id].id=id; currentLevelId=id; currentRoomId=id; syncSequence(); setMode('map'); }; $('sampleLevel').onclick=()=>{ currentLevelId=project.levels.sample_keep?'sample_keep':currentLevelId; currentRoomId=currentLevelId; setMode('map'); };
$('saveLocal').onclick=()=>{saveDraft(); status('Draft saved in this browser (localStorage). It will reload automatically next time.');}; $('exportJson').onclick=exportJSON; $('importJson').onchange=e=>{ importJSON(e.target.files[0]); e.target.value=''; }; $('saveFile').onclick=saveFile; $('playLevel').onclick=playLevel; $('uploadBg').onclick=uploadBg; $('addBgFit').onclick=()=>addBg($('bgLibrary').value); $('deleteSelectedBg').onclick=()=>{ if(selected?.kind==='bg') deleteSelected(); else status('Select a background first.'); }; $('newPath').onclick=addPath; $('clonePath').onclick=clonePath; $('deleteSelected').onclick=deleteSelected; $('addRouteCenter').onclick=()=>addRouteAt(currentCenter()); $('addEnemyCenter').onclick=()=>addEnemyAt(currentCenter()); $('addItemCenter').onclick=()=>addItemAt(currentCenter()); $('addWave').onclick=()=>{ const l=room(); l.waves.push({id:uid('wave'),trigger_x:0,gate_x:l.world.w-70,banner:'New room wave',enemies:[]}); saveDraft(); refreshAll(); };
$('zoomIn').onclick=()=>zoomAt(1.2); $('zoomOut').onclick=()=>zoomAt(1/1.2); $('zoomFit').onclick=fitView; $('zoomSlider').oninput=e=>{ view.z=+e.target.value/100; draw(); };
resize(); refreshAll(); setMode('map'); status('Ready: level map uses room boxes; open a room to paint background, depth, path, exits, and gameplay.');
})();